import { useState, useEffect } from "react";
import type { FormField, FormFieldOption } from "../../../types/form";
import { Button } from "../../ui/button";
import { Input } from "../../ui/input";
import { Label } from "../../ui/label";
import { Switch } from "../../ui/switch";
import { sanitizeFilenamePart } from "../../../lib/forms/pdf-generator";
import {
  X,
  Plus,
  Trash2,
  ChevronUp,
  ChevronDown,
  Check,
  AlertCircle,
} from "lucide-react";

interface FieldInspectorProps {
  field: FormField | null;
  isOpen: boolean;
  onClose: () => void;
  onSave: (updatedField: FormField) => void;
  existingFieldIds: string[];
}

export function FieldInspector({
  field,
  isOpen,
  onClose,
  onSave,
  existingFieldIds,
}: FieldInspectorProps) {
  const [draft, setDraft] = useState<FormField | null>(null);
  const [options, setOptions] = useState<FormFieldOption[]>([]);
  const [newOptionLabel, setNewOptionLabel] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isIdManuallyEdited, setIsIdManuallyEdited] = useState(false);

  const isAutoGeneratedId = (id?: string) => {
    if (!id || id === "field_id") return true;
    return /^(text|textarea|notes|num|date|time|datetime|select|choice|radio|check|checks|signature|head|note|field)_\d+(_copy_[a-z0-9]+)?$/.test(
      id,
    );
  };

  useEffect(() => {
    if (field) {
      setDraft(JSON.parse(JSON.stringify(field)));
      setOptions(
        field.options
          ? JSON.parse(JSON.stringify(field.options))
          : [
              { label: "Option 1", value: "option_1" },
              { label: "Option 2", value: "option_2" },
            ],
      );
      setError(null);
      setIsIdManuallyEdited(!isAutoGeneratedId(field.id));
    } else {
      setDraft(null);
      setOptions([]);
    }
  }, [field, isOpen]);

  if (!isOpen || !draft) return null;

  const handleLabelChange = (newLabel: string) => {
    setDraft((prev) => {
      if (!prev) return null;
      const updated = { ...prev, label: newLabel };
      if (!isIdManuallyEdited) {
        const slug = sanitizeFilenamePart(newLabel)
          .toLowerCase()
          .replace(/[^a-z0-9_]/g, "_")
          .replace(/^_+|_+$/g, "");
        if (slug) {
          updated.id = slug;
        }
      }
      return updated;
    });
    setError(null);
  };

  const handleAddOption = () => {
    const trimmed = newOptionLabel.trim();
    if (!trimmed) return;
    let valueSlug =
      sanitizeFilenamePart(trimmed)
        .toLowerCase()
        .replace(/[^a-z0-9_]/g, "_")
        .replace(/^_+|_+$/g, "") || `opt_${options.length + 1}`;

    if (options.some((o) => o.value === valueSlug)) {
      let counter = 2;
      while (options.some((o) => o.value === `${valueSlug}_${counter}`)) {
        counter++;
      }
      valueSlug = `${valueSlug}_${counter}`;
    }

    setOptions((prev) => [...prev, { label: trimmed, value: valueSlug }]);
    setNewOptionLabel("");
  };

  const handleUpdateOption = (
    index: number,
    key: "label" | "value",
    val: string,
  ) => {
    setOptions((prev) => {
      const next = [...prev];
      next[index] = { ...next[index], [key]: val };
      return next;
    });
  };

  const handleRemoveOption = (index: number) => {
    setOptions((prev) => prev.filter((_, i) => i !== index));
  };

  const handleMoveOption = (index: number, direction: "up" | "down") => {
    setOptions((prev) => {
      const next = [...prev];
      const targetIndex = direction === "up" ? index - 1 : index + 1;
      if (targetIndex < 0 || targetIndex >= next.length) return prev;
      const temp = next[index];
      next[index] = next[targetIndex];
      next[targetIndex] = temp;
      return next;
    });
  };

  const handleApply = () => {
    if (!draft.label.trim()) {
      setError("Field label is required.");
      return;
    }

    const cleanId = draft.id.trim();
    if (!cleanId) {
      setError("Field ID is required.");
      return;
    }

    if (!/^[a-zA-Z0-9_-]+$/.test(cleanId)) {
      setError(
        "Field ID must contain only letters, numbers, hyphens, and underscores (no spaces).",
      );
      return;
    }

    // Check duplicate ID (excluding self)
    const otherIds = existingFieldIds.filter((id) => id !== field?.id);
    if (otherIds.includes(cleanId)) {
      setError(
        `Field ID "${cleanId}" is already used by another field in this form.`,
      );
      return;
    }

    const hasOptions =
      draft.type === "select" ||
      draft.type === "radio" ||
      draft.type === "checkbox-group";

    if (hasOptions) {
      if (options.length === 0) {
        setError(
          `Please provide at least one option for this ${draft.type} field.`,
        );
        return;
      }
      const emptyLabel = options.find((opt) => !opt.label.trim());
      if (emptyLabel) {
        setError("All options must have a label.");
        return;
      }
      const emptyValue = options.find((opt) => !opt.value.trim());
      if (emptyValue) {
        setError("All options must have a value.");
        return;
      }
      const seenValues = new Set<string>();
      for (const opt of options) {
        const val = opt.value.trim();
        if (seenValues.has(val)) {
          setError(
            `Option value "${val}" is duplicated. Each option must have a unique value.`,
          );
          return;
        }
        seenValues.add(val);
      }
    }

    if (
      draft.type === "number" &&
      draft.validation?.min !== undefined &&
      draft.validation?.max !== undefined &&
      draft.validation.min > draft.validation.max
    ) {
      setError("Minimum value cannot be greater than maximum value.");
      return;
    }

    const canBeIdentifier =
      draft.type === "text" ||
      draft.type === "number" ||
      draft.type === "select" ||
      draft.type === "date";

    const finalField: FormField = {
      ...draft,
      id: cleanId,
      label: draft.label.trim(),
      isIdentifier: canBeIdentifier ? draft.isIdentifier : undefined,
      options: hasOptions ? options : undefined,
    };

    onSave(finalField);
    onClose();
  };

  const hasOptions =
    draft.type === "select" ||
    draft.type === "radio" ||
    draft.type === "checkbox-group";

  const canBeIdentifier =
    draft.type === "text" ||
    draft.type === "number" ||
    draft.type === "select" ||
    draft.type === "date";

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4 animate-in fade-in duration-150">
      <div className="bg-background rounded-2xl shadow-2xl border w-full max-w-xl max-h-[90vh] flex flex-col overflow-hidden">
        {/* Header */}
        <div className="p-4 sm:p-5 border-b flex items-center justify-between bg-muted/20 shrink-0">
          <div>
            <div className="flex items-center gap-2">
              <h3 className="font-bold text-lg text-foreground">
                Edit Field Properties
              </h3>
              <span className="text-[10px] font-mono uppercase tracking-wider font-semibold px-2 py-0.5 rounded bg-primary/10 text-primary">
                {draft.type}
              </span>
            </div>
            <p className="text-xs text-muted-foreground mt-0.5">
              Configure labels, rules, and options for this input field.
            </p>
          </div>
          <Button
            variant="ghost"
            size="icon"
            onClick={onClose}
            className="rounded-full"
            title="Cancel"
          >
            <X className="w-5 h-5" />
          </Button>
        </div>

        {/* Form Body */}
        <div className="p-4 sm:p-6 overflow-y-auto space-y-4 text-foreground">
          {error && (
            <div className="p-3 rounded-xl bg-destructive/10 border border-destructive/30 text-destructive text-xs flex items-center gap-2">
              <AlertCircle className="w-4 h-4 shrink-0" />
              <span>{error}</span>
            </div>
          )}

          {/* Label */}
          <div className="space-y-1.5">
            <Label htmlFor="field-label" className="text-xs font-semibold">
              Field Label <span className="text-destructive">*</span>
            </Label>
            <Input
              id="field-label"
              value={draft.label}
              onChange={(e) => handleLabelChange(e.target.value)}
              placeholder="e.g. Technician Name, Fluid Level, Inspection Date"
              className="text-sm"
              autoFocus
            />
          </div>

          {/* Field ID / Key */}
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <Label htmlFor="field-id" className="text-xs font-semibold">
                Field Key / ID <span className="text-destructive">*</span>
              </Label>
              <span className="text-[10px] text-muted-foreground">
                Used internally in saved JSON
              </span>
            </div>
            <Input
              id="field-id"
              value={draft.id}
              onChange={(e) => {
                setIsIdManuallyEdited(true);
                setDraft((prev) =>
                  prev ? { ...prev, id: e.target.value } : null,
                );
              }}
              placeholder="e.g. technician_name"
              className="font-mono text-xs"
            />
          </div>

          {/* Placeholder & Helper Text (for inputs) */}
          {draft.type !== "heading" && draft.type !== "notes" && (
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {draft.type !== "checkbox" && draft.type !== "signature" && (
                <div className="space-y-1.5">
                  <Label
                    htmlFor="field-placeholder"
                    className="text-xs font-semibold"
                  >
                    Placeholder Text
                  </Label>
                  <Input
                    id="field-placeholder"
                    value={draft.placeholder || ""}
                    onChange={(e) =>
                      setDraft((prev) =>
                        prev ? { ...prev, placeholder: e.target.value } : null,
                      )
                    }
                    placeholder="e.g. Enter details..."
                    className="text-xs"
                  />
                </div>
              )}

              <div className="space-y-1.5">
                <Label htmlFor="field-helper" className="text-xs font-semibold">
                  Helper Subtext
                </Label>
                <Input
                  id="field-helper"
                  value={draft.helperText || ""}
                  onChange={(e) =>
                    setDraft((prev) =>
                      prev ? { ...prev, helperText: e.target.value } : null,
                    )
                  }
                  placeholder="Optional instruction below field"
                  className="text-xs"
                />
              </div>
            </div>
          )}

          {/* Toggles: Required & IsIdentifier */}
          {draft.type !== "heading" && draft.type !== "notes" && (
            <div className="pt-2 border-t space-y-3">
              <div className="flex items-center justify-between p-3 rounded-xl border bg-muted/20">
                <div className="space-y-0.5 pr-4">
                  <span className="text-xs font-semibold">Required Field</span>
                  <p className="text-[11px] text-muted-foreground">
                    Must be completed before submitting the form.
                  </p>
                </div>
                <Switch
                  checked={draft.required || false}
                  onCheckedChange={(checked) =>
                    setDraft((prev) =>
                      prev ? { ...prev, required: checked } : null,
                    )
                  }
                />
              </div>

              {/* IsIdentifier toggle */}
              {canBeIdentifier && (
                <div className="flex items-start justify-between p-3 rounded-xl border bg-blue-500/5 border-blue-500/20">
                  <div className="space-y-1 pr-4">
                    <div className="flex items-center gap-1.5">
                      <span className="text-xs font-semibold text-blue-600 dark:text-blue-400">
                        Use as File Identifier
                      </span>
                    </div>
                    <p className="text-[11px] text-muted-foreground leading-relaxed">
                      Values entered here will be used in naming the submission
                      file and dated PDF snapshots (e.g.{" "}
                      <code className="bg-muted px-1 rounded font-mono text-[10px]">
                        Inspection_Truck-10_2026-09-04_1430.pdf
                      </code>
                      ).
                    </p>
                  </div>
                  <Switch
                    checked={draft.isIdentifier || false}
                    onCheckedChange={(checked) =>
                      setDraft((prev) =>
                        prev ? { ...prev, isIdentifier: checked } : null,
                      )
                    }
                  />
                </div>
              )}
            </div>
          )}

          {/* Default Value Settings */}
          {draft.type === "date" && (
            <div className="space-y-1.5 pt-2 border-t">
              <Label className="text-xs font-semibold">
                Default Date Value
              </Label>
              <div className="flex items-center gap-2">
                <Button
                  type="button"
                  size="xs"
                  variant={
                    draft.defaultValue === "today" ? "secondary" : "outline"
                  }
                  onClick={() =>
                    setDraft((prev) =>
                      prev ? { ...prev, defaultValue: "today" } : null,
                    )
                  }
                >
                  Default to Today's Date
                </Button>
                <Button
                  type="button"
                  size="xs"
                  variant={!draft.defaultValue ? "secondary" : "outline"}
                  onClick={() =>
                    setDraft((prev) =>
                      prev ? { ...prev, defaultValue: undefined } : null,
                    )
                  }
                >
                  Leave Blank
                </Button>
              </div>
            </div>
          )}

          {draft.type === "datetime" && (
            <div className="space-y-1.5 pt-2 border-t">
              <Label className="text-xs font-semibold">
                Default Timestamp Value
              </Label>
              <div className="flex items-center gap-2">
                <Button
                  type="button"
                  size="xs"
                  variant={
                    draft.defaultValue === "now" ? "secondary" : "outline"
                  }
                  onClick={() =>
                    setDraft((prev) =>
                      prev ? { ...prev, defaultValue: "now" } : null,
                    )
                  }
                >
                  Default to Current Date & Time
                </Button>
                <Button
                  type="button"
                  size="xs"
                  variant={!draft.defaultValue ? "secondary" : "outline"}
                  onClick={() =>
                    setDraft((prev) =>
                      prev ? { ...prev, defaultValue: undefined } : null,
                    )
                  }
                >
                  Leave Blank
                </Button>
              </div>
            </div>
          )}

          {draft.type === "number" && (
            <div className="space-y-1.5 pt-2 border-t">
              <Label className="text-xs font-semibold">
                Optional Bounds (Validation)
              </Label>
              <div className="grid grid-cols-2 gap-3">
                <Input
                  type="number"
                  placeholder="Min value"
                  value={draft.validation?.min ?? ""}
                  onChange={(e) => {
                    const min =
                      e.target.value !== ""
                        ? Number(e.target.value)
                        : undefined;
                    setDraft((prev) =>
                      prev
                        ? {
                            ...prev,
                            validation: { ...prev.validation, min },
                          }
                        : null,
                    );
                  }}
                  className="text-xs"
                />
                <Input
                  type="number"
                  placeholder="Max value"
                  value={draft.validation?.max ?? ""}
                  onChange={(e) => {
                    const max =
                      e.target.value !== ""
                        ? Number(e.target.value)
                        : undefined;
                    setDraft((prev) =>
                      prev
                        ? {
                            ...prev,
                            validation: { ...prev.validation, max },
                          }
                        : null,
                    );
                  }}
                  className="text-xs"
                />
              </div>
            </div>
          )}

          {/* Options Manager for choices */}
          {hasOptions && (
            <div className="space-y-3 pt-3 border-t">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="text-xs font-semibold">Choice Options</h4>
                  <p className="text-[11px] text-muted-foreground">
                    Available selections for field workers.
                  </p>
                </div>
                <span className="text-[10px] font-mono text-muted-foreground">
                  {options.length} option{options.length === 1 ? "" : "s"}
                </span>
              </div>

              {/* Add option row */}
              <div className="flex items-center gap-2">
                <Input
                  value={newOptionLabel}
                  onChange={(e) => setNewOptionLabel(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") {
                      e.preventDefault();
                      handleAddOption();
                    }
                  }}
                  placeholder="Add new option label..."
                  className="text-xs flex-1"
                />
                <Button
                  type="button"
                  size="xs"
                  onClick={handleAddOption}
                  disabled={!newOptionLabel.trim()}
                  className="gap-1 font-semibold"
                >
                  <Plus className="w-3.5 h-3.5" />
                  Add
                </Button>
              </div>

              {/* Options list */}
              <div className="space-y-1.5 max-h-48 overflow-y-auto pr-1">
                {options.map((opt, idx) => (
                  <div
                    key={idx}
                    className="flex items-center gap-2 p-1.5 rounded-lg border bg-card text-xs"
                  >
                    <div className="flex flex-col gap-0.5">
                      <button
                        type="button"
                        onClick={() => handleMoveOption(idx, "up")}
                        disabled={idx === 0}
                        className="text-muted-foreground hover:text-foreground disabled:opacity-30"
                        title="Move Up"
                      >
                        <ChevronUp className="w-3.5 h-3.5" />
                      </button>
                      <button
                        type="button"
                        onClick={() => handleMoveOption(idx, "down")}
                        disabled={idx === options.length - 1}
                        className="text-muted-foreground hover:text-foreground disabled:opacity-30"
                        title="Move Down"
                      >
                        <ChevronDown className="w-3.5 h-3.5" />
                      </button>
                    </div>

                    <Input
                      value={opt.label}
                      onChange={(e) =>
                        handleUpdateOption(idx, "label", e.target.value)
                      }
                      placeholder="Option label"
                      className="text-xs flex-1 h-7"
                    />

                    <Input
                      value={opt.value}
                      onChange={(e) =>
                        handleUpdateOption(idx, "value", e.target.value)
                      }
                      placeholder="Value"
                      className="text-xs w-28 h-7 font-mono text-muted-foreground"
                      title="Value stored in data"
                    />

                    <Button
                      type="button"
                      variant="ghost"
                      size="icon-xs"
                      onClick={() => handleRemoveOption(idx)}
                      className="text-muted-foreground hover:text-destructive shrink-0"
                      title="Remove option"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </Button>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t flex items-center justify-end gap-2 bg-muted/10 shrink-0">
          <Button variant="outline" size="sm" onClick={onClose}>
            Cancel
          </Button>
          <Button
            size="sm"
            onClick={handleApply}
            className="gap-1.5 font-semibold"
          >
            <Check className="w-4 h-4" />
            Apply Changes
          </Button>
        </div>
      </div>
    </div>
  );
}
